### PR TITLE
Add ability to call module as CLI utility (`python -m`)

### PR DESCRIPTION
**Pull request by tribals**
It is very usable package, but it is also very annoying to copy-paste same simple script again and again in every project I'm working on (that uses XML) to get the ability to quickly convert some unreadable messy XML to eye-pleasant well-formatted easily understandable JSON one.

### CODE REVIEW

**Comment by tribals** [comment]
Unfortunately, there is no tests - I can not figure out how to write kinda integration test for CLI tool, at least using `unittest`. As for the unit tests, I think there is no need for it - the code is dead simple, it doesn't bring any changes to conversion algorithms.

**Comment by sanand0** [comment]
@tribals -- I've refactored this and added test cases in the [cli](https://github.com/sanand0/xmljson/tree/cli) branch. Does this work for you?

**Comment by tribals** [comment]
@sanand0 I've played with it for a while - works just fine, thanks!

**Comment by sanand0** [comment]
@tribals -- great, closing this and merging the `cli` branch into master.

**Pull request closed without merging**
